server:
  port: 80
  
elasticsearch:
  schema: http
  address: 127.0.0.1:9200
  connectTimeout: 600000
  socketTimeout: 600000
  connectionRequestTimeout: 600000
  maxConnectNum: 100
  maxConnectPerRoute: 100

  