server:
  port: 80

jasypt:
  encryptor:
    password: qwera@12345

spring:
  datasource:
    name: external-data
    username: ${database.username}
    password: ${database.password}
    url: jdbc:mysql://${database.host}:${database.port}/${database.dbname}?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 3600000
  redis: 
    url: redis://127.0.0.1:6379
    database: 0
    password: 123456
#    redisson: 
#      file: classpath:redisson.yml
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      acks: 1



database:
  username: ENC(3W6u5nkhzyoAucXe8lVoeg==)
  password: ENC(U+3vFrEXFMo9G5ThhXi3QA==)
  host: ENC(zU8yIGZfgCeFx+Sx8/nsM6RUU6Evy+Q0)
  port: ENC(NY2q530m71cO+c4oZNDaWA==)
  dbname: ENC(becneSOoLJya/QjNA4X8oMcOuJF0Bbvy)
#elasticsearch:
#  schema: http
#  address: 127.0.0.1:9200
#  connectTimeout: 600000
#  socketTimeout: 600000
#  connectionRequestTimeout: 600000
#  maxConnectNum: 100
#  maxConnectPerRoute: 100

logging:
  config: classpath:log4j2.xml

