server:
  port: 80

spring:
  datasource:
    name: external-data
    username: ${database.username}
    password: ${database.password}
    url: jdbc:mysql://${database.host}:${database.port}/${database.dbname}?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 3600000

database:
  username: root
  password: root
  host: localhost
  port: 3306
  dbname: datacenter

elasticsearch:
  schema: http
  address: 127.0.0.1:9200
  connectTimeout: 600000
  socketTimeout: 600000
  connectionRequestTimeout: 600000
  maxConnectNum: 100
  maxConnectPerRoute: 100
  
debug: true
logging:
  level:
    xyz.ganghua: debug





