server:
  port: 80
  
 
#spring:
#  elasticsearch:
#    rest:
#      uris:
#      - 192.168.50.97:9200
#      username: elastic
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
